language: cpp

jobs:
    include:
        - os: linux
          dist: focal
          compiler: gcc
          env:
              - GCC_VER="9"
              - MATRIX_EVAL="CC=gcc-${GCC_VER} && CXX=g++-${GCC_VER}"
          addons:
              apt:
                  source:
                      - ubuntu-toolchain-r-test
                  packages:
                      - gcc-9
                      - g++-9
                      - doxygen
        - os: linux
          dist: focal
          compiler: gcc
          env:
              - GCC_VER="10"
              - MATRIX_EVAL="CC=gcc-${GCC_VER} && CXX=g++-${GCC_VER}"
          addons:
              apt:
                  source:
                      - ubuntu-toolchain-r-test
                  packages:
                      - gcc-10
                      - g++-10
        - os: linux
          dist: focal
          compiler: clang
          env:
              - CLANG_VER="10"
              - MATRIX_EVAL="CC=clang-${CLANG_VER} && CXX=clang++-${CLANG_VER}"
          addons:
              apt:
                  source:
                      - ubuntu-toolchain-r-test
                  packages:
                      - clang-10
                      - clang++-10
before_script:
    - eval "${MATRIX_EVAL}"

script:
    - mkdir build
    - cd build
    - cmake .. -GNinja
    - ninja tests
